`default_nettype none

`include "rv32i_params.vh"
`include "rv32i_defs.vh"

//==============================================================
// Module      : alu_control
// Description :
//   ALU Control Unit for the RV32I processor.
//
//   Converts the high-level ALU operation class generated by
//   the Main Control Unit and the instruction's funct3/funct7
//   fields into the 4-bit operation code understood by the ALU.
//
// Inputs:
//   - ALUOp  : Operation class from Main Control Unit
//   - funct3 : Instruction funct3 field
//   - funct7 : Instruction funct7 field
//
// Output:
//   - alu_control : Operation code for the ALU
//
// ALUOp:
//   00 -> Address calculation / ADD
//   01 -> Branch comparison / SUB
//   10 -> R-Type / I-Type ALU operation
//
// Target FPGA : Xilinx Artix-7 (Basys-3)
//==============================================================

module alu_control (
    //----------------------------------------------------------
    // Control Inputs
    //----------------------------------------------------------

    input wire [1:0] ALUOp,

    //----------------------------------------------------------
    // Instruction Fields
    //----------------------------------------------------------

    input wire [2:0] funct3,
    input wire [6:0] funct7,

    //----------------------------------------------------------
    // ALU Operation Output
    //----------------------------------------------------------

    output reg [3:0] alu_control
);

    //----------------------------------------------------------
    // ALU Control Logic
    //----------------------------------------------------------

    always @(*) begin

        //------------------------------------------------------
        // Safe Default
        //------------------------------------------------------

        alu_control = `ALU_ADD;

        //------------------------------------------------------
        // Decode ALU Operation Class
        //------------------------------------------------------

        case (ALUOp)

            //--------------------------------------------------
            // Address Calculation
            //
            // Used by:
            //   Load
            //   Store
            //   JALR
            //
            // Operation:
            //   Base Register + Immediate
            //--------------------------------------------------

            2'b00: begin

                alu_control = `ALU_ADD;

            end

            //--------------------------------------------------
            // Branch Comparison
            //
            // Initial implementation uses subtraction so that
            // the ALU zero flag can be used for equality.
            //--------------------------------------------------

            2'b01: begin

                alu_control = `ALU_SUB;

            end

            //--------------------------------------------------
            // R-Type / I-Type ALU Operations
            //--------------------------------------------------

            2'b10: begin

                case (funct3)

                    //--------------------------------------------------
                    // ADD / ADDI
                    // SUB
                    //--------------------------------------------------

                    3'b000: begin

                        if (funct7 == 7'b0100000)
                            alu_control = `ALU_SUB;
                        else
                            alu_control = `ALU_ADD;

                    end

                    //--------------------------------------------------
                    // SLL / SLLI
                    //--------------------------------------------------

                    3'b001: begin

                        alu_control = `ALU_SLL;

                    end

                    //--------------------------------------------------
                    // SLT / SLTI
                    //--------------------------------------------------

                    3'b010: begin

                        alu_control = `ALU_SLT;

                    end

                    //--------------------------------------------------
                    // SLTU / SLTIU
                    //--------------------------------------------------

                    3'b011: begin

                        alu_control = `ALU_SLTU;

                    end

                    //--------------------------------------------------
                    // XOR / XORI
                    //--------------------------------------------------

                    3'b100: begin

                        alu_control = `ALU_XOR;

                    end

                    //--------------------------------------------------
                    // SRL / SRA
                    // SRLI / SRAI
                    //--------------------------------------------------

                    3'b101: begin

                        if (funct7 == 7'b0100000)
                            alu_control = `ALU_SRA;
                        else
                            alu_control = `ALU_SRL;

                    end

                    //--------------------------------------------------
                    // OR / ORI
                    //--------------------------------------------------

                    3'b110: begin

                        alu_control = `ALU_OR;

                    end

                    //--------------------------------------------------
                    // AND / ANDI
                    //--------------------------------------------------

                    3'b111: begin

                        alu_control = `ALU_AND;

                    end

                    //--------------------------------------------------
                    // Unsupported funct3
                    //--------------------------------------------------

                    default: begin

                        alu_control = `ALU_ADD;

                    end

                endcase

            end

            //--------------------------------------------------
            // Unsupported ALUOp
            //--------------------------------------------------

            default: begin

                alu_control = `ALU_ADD;

            end

        endcase

    end

endmodule

`default_nettype wire