`default_nettype none

`include "rv32i_params.vh"

//==============================================================
// Module      : program_counter
// Description :
//   Program Counter (PC) for the RV32I processor.
//
// Features:
//   - Parameterized data width
//   - Synchronous reset
//   - Synchronous write enable
//   - External next PC input
//
// Notes:
//   - The Program Counter does NOT calculate the next address.
//   - The next PC value is generated by the datapath/control
//     logic and supplied through the 'pc_next' input.
//   - This design supports future branch, jump, and pipeline
//     extensions without modification.
//
// Target FPGA : Xilinx Artix-7 (Basys-3)
//==============================================================

module program_counter #(
    parameter DATA_WIDTH = 32
)(
    //----------------------------------------------------------
    // Clock and Reset
    //----------------------------------------------------------

    input  wire                  clk,
    input  wire                  rst,

    //----------------------------------------------------------
    // Control
    //----------------------------------------------------------

    input  wire                  pc_write,

    //----------------------------------------------------------
    // Next Program Counter
    //----------------------------------------------------------

    input  wire [DATA_WIDTH-1:0] pc_next,

    //----------------------------------------------------------
    // Current Program Counter
    //----------------------------------------------------------

    output reg  [DATA_WIDTH-1:0] pc
);

    //----------------------------------------------------------
    // Program Counter Register
    //----------------------------------------------------------

    always @(posedge clk) begin

        if (rst) begin

            pc <= `RESET_VECTOR;

        end

        else if (pc_write) begin

            pc <= pc_next;

        end

    end

endmodule

`default_nettype wire